server:
  port: 6666
swagger:
  enable: true


spring:
#  redis:
##  redis第0个库
#    database: 0
##    地址
#    host: localhost
##    端口
#    port: 6379
##    密码
#    password: 123456
#    集群模式  如果需要，把host和port禁用，开启下面cluster.nodes即可
#    cluster:
#      nodes:
#      - 127.0.0.1:6379
#      - 127.0.0.1:6380
#      - 127.0.0.1:6381
#      - 127.0.0.1:6388
#   此处不适用jedis线程池，因为是非线程安全。如果出现多线程抢夺资源，redis串行操作数据异常。另外jedis连接数量过多，资源消耗阶梯式增大，连接成本就较高。
#  lettuce:
#    pool:
#      #      连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      #        连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1ms
#      #        连接池中的最大空闲连接
#      max-idle: 8
#      #        连接池中的最小空闲连接
#      min-idle: 0
#  #    连接超时时间（毫秒）
#  timeout: 30000ms
  datasource:
    #    配置这个属性的意义在于，如果存在多个数据源，监控的时候可以通过名字来区分开来。 如果没有配置，将会生成一个名字，格式是："DataSource-" + System.identityHashCode(this)
    name: druidDataSource
    #    连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/seeding?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: myroot2020
      #      配置监控统计拦截的filters，去掉后监控界面sql无法进行统计。wall:防御sql注入 stat:监控统计
      filters: stat,wall,config
      #      最大连接数
      max-active: 20
      #      初始化大小
      initial-size: 1
      #      获取连接等待超时时间（毫秒）
      max-wait: 60000
      #      最小连接数
      min-idle: 1
      #      间隔多久才进行一次检测。检测需要关闭的空闲连接（毫秒）
      time-between-eviction-runs-millis: 60000
      #      一个连接在池中最小生存的时间（毫秒）
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'  # 用来检测连接是否有效的sql
      test-while-idle: true # 	建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。 获取到了不可用的数据库连接，一般由应用处理异常。
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。【出于性能考虑一般生产环境不开启】
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能【出于性能考虑一般生产环境不开启】
      pool-prepared-statements: false  # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      max-open-prepared-statements: -1  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
  # 打开PSCache，并且指定每个连接上PSCache的大小
  #      pool-prepared-statements: true  # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
  #      max-open-prepared-statements: 100  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
  #      max-pool-prepared-statement-per-connection-size: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/seeding?characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    username: root
#    password: myroot2020
#    driver-class-name: com.mysql.jdbc.Driver


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##  mapper-locations: classpath:/com/enike/admin/mapper/*.xml,classpath:/com/enike/admin/mapper/*/*.xml,classpath*:/com/**/admin/mapper/*.xml
##  type-aliases-package: com.enike.admin.entity
#  mapper-locations: classpath:/com/enike/admin/mapper/*.xml,classpath:/com/enike/admin/mapper/*/*.xml
#  typeAliasesPackage: com.enike.admin.entity

mybatis-plus:
  mapper-locations: classpath:/com/enike/admin/mapper/*.xml,classpath:/com/enike/admin/mapper/*/*.xml
  typeAliasesPackage: com.enike.admin.entity
  configuration:
    map-underscore-to-camel-case: true
